### ISSUE TITLE
Tag v0.9.4rc1?

### ISSUE THREAD

**Issue by danielballan** [soft-matter/slicerator#11]
There is a change to the private API (hook -> flag) and a build fix. OK if I tag v0.9.4rc1?

**Comment by caspervdw** [comment]
I am not sure if an rc is necessary. But a tag is ok with me!
Op 4 nov. 2015 17:25 schreef "Dan Allan" notifications@github.com:

There is a change to the private API (hook -> flag) and a build fix. OK if
I tag v0.9.4rc1?

—
Reply to this email directly or view it on GitHub
https://github.com/soft-matter/slicerator/issues/11.

**Comment by danielballan** [comment]
OK, I'll go straight for the tag. This one is straightforward. After my
slew of careless errors last time, I wanted to offer you the opportunity to
put on the breaks. :- D

Dan

**Comment by danielballan** [comment]
P.S. Is it time for v0.3.2 final as well?

**Comment by caspervdw** [comment]
Yes, we should release that and get on with trackpy v0.3

**Comment by danielballan** [comment]
Great. Will do today. I am making progress on getting PyAV and tifffile
build on current versions.

**Comment by caspervdw** [comment]
I found a bug in PIMS... please give me some more time to solve it before 0.3.2 ;)

**Comment by danielballan** [comment]
Gotcha!
