### ISSUE TITLE
Allow for property-changing processing functions

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/slicerator#16]
Some issue I already encountered several times: if you crop a reader, the `frame_shape` will change. Or if you make a reader grayscale, the color depth will change. Currently there is no way to account for that.

I guess the solution will be a `Pipeline` class that can be subclassed for these more advanced pipeline functions. Also we might need some more standardization of `Frame` metadata fields (but that's for pims).

**Comment by danielballan** [comment]
Yes, I've had this issue as well. When we include some crop functions in pims, which I think we planned on doing soon, they should alter `frame_shape` appropriately.

**Comment by caspervdw** [comment]
Closed by #21
