### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/slicerator#3]
What's going on with the version? On pypi it says 0.9.2 .. https://pypi.python.org/pypi/slicerator

**Comment by danielballan** [comment]
Yeah, I started with v0.9 to communicate to scikit-image folks (etc.) that we aim to commit to a stable API (1.0) in the near future. We can tag as many 0.9.x's as we need to until we are happy, but I hope to commit to something soon. Tom did something similar with [cycler](https://github.com/matplotlib/cycler/releases).

With simple a utility package like this, one hopes that there will be little or no ongoing development once the API is correct.

**Comment by caspervdw** [comment]
Ah I see, thanks for the explanation ;)
