### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jakirkham** [soft-matter/slicerator#35]
Would it be possible to get a new release?

**Comment by danielballan** [comment]
@nkeim @caspervdw Any reason not to roll a release at this point? I'm willing to go through the motions, but since I haven't been closely engaged in awhile I don't want to unilaterally do this for fear of pushing out something half-baked.

**Comment by nkeim** [comment]
Whoa! I have finally looked at this and a LOT has happened since the last release. Sorry for the delay, @jakirkham . Yes, I think we are indeed ready. @danielballan would you still be able to do the release?

Also, should this be v1.0 ??? It sure looks like it to me.

**Comment by danielballan** [comment]
Sure. I'll aim to do this in the next 1-2 weeks.

**Comment by jakirkham** [comment]
Just curious, have you had a chance to look, @danielballan? Do you need help with anything in particular?

**Comment by danielballan** [comment]
Thanks for the nudge. v1.0.0rc1 is [on PyPI](https://pypi.org/project/slicerator/1.0.0rc1/). Let's let that sit for a bit and I'll tag v1.0.0a week from today if we don't discover any problems.

**Comment by danielballan** [comment]
v1.0.0 is up!

**Comment by marscher** [comment]
It seems there is no git tag for version 1.0.0

Being off-topic, can we expect a new micro release for supporting Python 3.10+ any soon?
