### ISSUE TITLE
Please release!

### ISSUE THREAD

**Issue by marscher** [soft-matter/slicerator#41]
It be great to have Python 3.10+ support. It seems like this has already be done in #40, but we need a release to be usable in packages like pims etc.
Thank you so much for your effort to maintain this package!

**Comment by nkeim** [comment]
Pinging @tacaswell . I would be glad to help with bits of this work in mid to late April, assuming there's still some to be done.

**Comment by tacaswell** [comment]
This has been on my to-do list.  I was trying to do both slicerator and pims releases and ended up falling into https://github.com/soft-matter/pims/pull/399

**Comment by marscher** [comment]
Couldn't you apply the same github actions you implemented for pims just for slicerator as well? If any help is needed, I can see what can be done.

**Comment by tacaswell** [comment]
Done!

```
$ pip install --upgrade slicerator
Requirement already satisfied: slicerator in /home/tcaswell/.virtualenvs/sys310/lib/python3.10/site-packages (1.0.0)
Collecting slicerator
  Downloading slicerator-1.1.0-py3-none-any.whl (10 kB)
Installing collected packages: slicerator
  Attempting uninstall: slicerator
    Found existing installation: slicerator 1.0.0
    Uninstalling slicerator-1.0.0:
      Successfully uninstalled slicerator-1.0.0
Successfully installed slicerator-1.1.0
```

@marscher It was faster for me to just do it, but would be very happy to merge automated pypi pushing!
