### ISSUE TITLE
0.9.3 on conda?

### ISSUE THREAD

**Issue by nkeim** [soft-matter/slicerator#9]
The pending version of pims seems to require slicerator v0.9.3, but 0.9.2 is the latest version I find on the "soft-matter" channel.

**Comment by danielballan** [comment]
Yes. I'm on it. I'll do some packaging today. I need it for work anyway.

**Comment by danielballan** [comment]
Packages for slicerator v0.9.4 for all five platforms and Python 2.6, 2.7, 3.3, 3.4, and 3.5 are on the soft-matter channel.

https://anaconda.org/soft-matter/slicerator/
